###
# 获取验证码
GET http://{{host}}:{{port}}/api/captcha/register/1174446068@qq.com/
Accept: application/json

###
# 用户注册
POST http://{{host}}:{{port}}/api/user/register/
Accept: application/json

{
  "username": "蔡蔡",
  "email": "1174446068@qq.com",
  "password": "Abcd1234",
  "captcha": "221845"
}


###
# 登陆 - 成功用例
POST http://{{host}}:{{port}}/api/user/login/
Accept: application/json

{
  "email": "1174446068@qq.com",
  "password": "Abcd1234"
}

###
# 登陆 - 账号用户不存在
POST http://{{host}}:{{port}}/api/user/login/
Accept: application/json

{
  "email": "1174446069@qq.com",
  "password": "Abcd12346"
}

###
# 登陆 - 密码错误
POST http://{{host}}:{{port}}/api/user/login/
Accept: application/json

{
  "email": "1174446068@qq.com",
  "password": "Abcd12346"
}


